### ISSUE TITLE
Chyby ve formulářích a ve stylu na kontaktní stránce

### ISSUE THREAD

**Issue by screamy159** [Werfmon/Pachota-photo-web#2]
Při odeslání dat pomocí formuláře se pole vyprázdní, poté co do jednoho z polí napíšu jakoukoliv hodnotu, všechny pole kromě aktuálně vybraného nabydou předchozí hodnotou

Při zadání neplatného emailu se rozbije border

**Comment by Werfmon** [comment]
Vše už je opraveno, díky.
